import unittest
import sys
sys.path.insert(0, 'year2024')
from src.day8 import Day8

class TestDay8(unittest.TestCase):

    def setUp(self):
        self.example_input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
        self.day8_instance = Day8(self.example_input)

    def test_part1(self):
        result = self.day8_instance.part1()
        self.assertEqual(result, 14)

    def test_part2(self):
        result = self.day8_instance.part2()
        self.assertEqual(result, 34)

if __name__ == '__main__':
    unittest.main()
